# Etapa de Build
FROM node:lts-alpine AS build
WORKDIR /app
# Cache de dependências
COPY package*.json ./
RUN npm install
COPY . .
COPY .env.production .env.production
RUN npm run build

# Etapa de Produção
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/.env.production /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]