services:
  planning-voter-web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
    environment:
      - PORT=3001
      - WDS_SOCKET_PORT=3001
      - WDS_SOCKET_HOST=localhost
      - REACT_APP_SOCKET_URL=http://localhost:4000
    command: npm start
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
    environment:
      NODE_ENV: development
      CLIENT_URL: "http://localhost:3001"
      API_PORT: 4000
    command: npm start
