services:
  planning-voter-web:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
