services:
  planning-voter-web:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server
    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    command: node server.js
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    depends_on:
      - planning-voter-web
      - server

networks:
  app_network:
    driver: bridge