version: "3"  # Versão do Docker Compose

services:
  planning-voter-web:  # Nome do serviço da aplicação web
    build: .  # Caminho para o Dockerfile da aplicação web
    ports:
      - "3000:3000"  # Porta que será exposta para acessar a aplicação web
    volumes:
      - .:/app  # Mapeamento do diretório local para o diretório do container da aplicação web
      - /app/node_modules
    command: npm start  # Comando para iniciar a aplicação web