services:
  planning-voter-web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env.development
    environment:
      - NODE_ENV=development
      - PORT=3001
      - WDS_SOCKET_PORT=3001
      - WDS_SOCKET_HOST=localhost
      - REACT_APP_API_URL=http://localhost:4000/api
      - REACT_APP_SOCKET_URL=http://localhost:4000
    command: npm start
    depends_on:
      - server
    networks:
      - dev-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3001
      - API_PORT=4000
    env_file:
      - ./server/.env.development
    command: npm run dev
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
