services:
  planning-voter-web:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - /etc/letsencrypt/live/charlesmuller.dev.br:/etc/letsencrypt:ro
    depends_on:
      - server
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    command: node server.js