# Imagem base
FROM mysql:8

# Define as variáveis de ambiente necessárias para o MySQL
ENV MYSQL_DATABASE=your_database_name_here \
    MYSQL_USER=your_mysql_username_here \
    MYSQL_PASSWORD=your_mysql_password_here \
    MYSQL_ROOT_PASSWORD=your_mysql_root_password_here

